name: ESN_Client_App

on:
  push:
    branches:
      - Deploy_Test_Branch
  pull_request:
    branches:
      - Deploy_Test_Branch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm --prefix client install

    - name: Build
      run: npm --prefix client update caniuse-lite browserslist && CI=false npm --prefix client run build

    - name: Deploy to GitHub Pages
      run: |
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          echo "node_modules" >> .gitignore
          echo ".github" >> .gitignore
          git --prefix client add .
          git commit -m "Deploy to GitHub Pages"
          git branch -D gh-pages || true
          git checkout -b gh-pages
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages

